import { CatalogSeedItem } from './catalog-seed-item.model';

export const CATALOG_SEED_DATA: CatalogSeedItem[] = [
  {
    id: 1,
    slug: 'lemon-garlic-shrimp-pasta',
    name: 'Lemon-Garlic Shrimp Pasta',
    description: 'Silky garlic butter pasta tossed with shrimp, lemon zest and fresh herbs.',
    longDescription: 'Use fresh lemon juice and zest for the brightest flavor. Pull shrimp off heat when just pink â€” they continue cooking from residual heat.',
    imgUrl: 'https://images.unsplash.com/photo-1762631178604-3b79d4d0bff9?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A plate of lemon-garlic shrimp pasta garnished with parsley',
    price: 42,
    category: 'Pasta',
    tags: ['seafood', 'pasta', 'quick', 'garlic'],
    rating: 4.8,
    reviewCount: 1240,
    highlights: ['Pasta', 'Italian', 'seafood', 'pasta', 'quick'],
  },
  {
    id: 2,
    slug: 'mediterranean-quinoa-salad',
    name: 'Mediterranean Quinoa Salad',
    description: 'A bright grain salad with cucumber, tomato, herbs and creamy feta.',
    longDescription: 'Make ahead and refrigerate â€” the flavors develop and get even better overnight.',
    imgUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A colorful quinoa salad bowl with feta, tomatoes and cucumber',
    price: 45,
    category: 'Salad',
    tags: ['salad', 'healthy', 'vegetarian', 'meal-prep'],
    rating: 4.5,
    reviewCount: 870,
    highlights: ['Salad', 'Mediterranean', 'salad', 'healthy', 'vegetarian'],
  },
  {
    id: 3,
    slug: 'roasted-veggie-buddha-bowl',
    name: 'Roasted Veggie Buddha Bowl',
    description: 'Oven-roasted vegetables, grains and creamy dressing in a hearty bowl.',
    longDescription: 'Massage kale with a little oil and salt if adding greens â€” it softens the texture beautifully.',
    imgUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A hearty buddha bowl with roasted sweet potato, broccoli, chickpeas and tahini',
    price: 48,
    compareAtPrice: 56,
    category: 'Bowl',
    tags: ['bowl', 'vegan', 'roasted', 'healthy'],
    rating: 4.7,
    reviewCount: 1560,
    highlights: ['Bowl', 'Fusion', 'bowl', 'vegan', 'roasted'],
  },
  {
    id: 4,
    slug: 'new-york-strip-steak',
    name: 'New York Strip Steak',
    description: 'Seared steakhouse-style with buttered green beans and pan sauce.',
    longDescription: 'Let the steak rest â€” this redistributes juices for a more tender, flavorful bite.',
    imgUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A perfectly seared New York strip steak with green beans',
    price: 51,
    category: 'Steak',
    tags: ['steak', 'dinner', 'cast-iron', 'protein'],
    rating: 4.9,
    reviewCount: 3180,
    highlights: ['Steak', 'American', 'steak', 'dinner', 'cast-iron'],
  },
  {
    id: 5,
    slug: 'thai-green-curry-chicken',
    name: 'Thai Green Curry Chicken',
    description: 'Creamy coconut curry with chicken, herbs and bright green vegetables.',
    longDescription: 'Toast the curry paste in oil before adding coconut milk â€” it deepens the flavor significantly.',
    imgUrl: 'https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A bowl of Thai green curry chicken with basil and coconut cream',
    price: 54,
    category: 'Curry',
    tags: ['curry', 'chicken', 'spicy', 'coconut'],
    rating: 4.6,
    reviewCount: 2010,
    highlights: ['Curry', 'Thai', 'curry', 'chicken', 'spicy'],
  },
  {
    id: 6,
    slug: 'sesame-chicken-rice-bowl',
    name: 'Sesame Chicken Rice Bowl',
    description: 'A warm bowl layered with roasted vegetables, fluffy rice and tender sesame-glazed chicken.',
    longDescription: 'Toast the sesame seeds in a dry pan for 1 minute to unlock their nutty aroma.',
    imgUrl: 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A sesame chicken rice bowl with broccoli and carrots',
    price: 57,
    compareAtPrice: 65,
    category: 'Bowl',
    tags: ['bowl', 'chicken', 'sesame', 'rice'],
    rating: 4.3,
    reviewCount: 640,
    highlights: ['Bowl', 'Asian', 'bowl', 'chicken', 'sesame'],
  },
  {
    id: 7,
    slug: 'roasted-veggie-stir-fry-noodles',
    name: 'Roasted Veggie Stir-Fry Noodles',
    description: 'Pan-finished noodles with colorful roasted vegetables and savory soy-ginger sauce.',
    longDescription: 'High heat is key â€” it gives the noodles that slightly smoky wok flavor even in a regular pan.',
    imgUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A plate of stir-fry noodles with roasted vegetables and mushrooms',
    price: 60,
    category: 'Stir-Fry',
    tags: ['noodles', 'vegetarian', 'stir-fry', 'quick'],
    rating: 4.4,
    reviewCount: 1780,
    highlights: ['Stir-Fry', 'Asian', 'noodles', 'vegetarian', 'stir-fry'],
  },
  {
    id: 8,
    slug: 'herb-basted-skillet-chicken',
    name: 'Herb-Basted Skillet Chicken',
    description: 'Juicy skillet chicken basted in herb butter, served with crispy potatoes and roasted broccoli.',
    longDescription: 'Pat the chicken dry before searing â€” moisture is the enemy of a crispy golden skin.',
    imgUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Herb-basted chicken in a cast-iron skillet with potatoes',
    price: 63,
    compareAtPrice: 75,
    category: 'Main Course',
    tags: ['chicken', 'skillet', 'comfort', 'one-pan'],
    rating: 4.7,
    reviewCount: 2350,
    highlights: ['Main Course', 'American', 'chicken', 'skillet', 'comfort'],
  },
  {
    id: 9,
    slug: 'creamy-tuscan-chicken-pasta',
    name: 'Creamy Tuscan Chicken Pasta',
    description: 'Creamy pasta with seared chicken, sun-dried tomatoes, spinach and a rich garlic parmesan finish.',
    longDescription: 'Deglaze the pan after searing the chicken â€” those brown bits are pure flavor.',
    imgUrl: 'https://images.unsplash.com/photo-1724116382285-f4fcbe27f6a1?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Creamy Tuscan chicken pasta with spinach and parmesan',
    price: 66,
    compareAtPrice: 74,
    category: 'Pasta',
    tags: ['pasta', 'chicken', 'creamy', 'comfort'],
    rating: 4.2,
    reviewCount: 540,
    highlights: ['Pasta', 'Italian', 'pasta', 'chicken', 'creamy'],
  },
  {
    id: 10,
    slug: 'thai-coconut-shrimp-curry',
    name: 'Thai Coconut Shrimp Curry',
    description: 'Fragrant curry broth with shrimp, basil, lime and silky coconut richness.',
    longDescription: 'Add the shrimp at the very end â€” overcooking makes them rubbery. Serve with steamed jasmine rice.',
    imgUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A fragrant Thai coconut shrimp curry with lime and basil',
    price: 69,
    category: 'Curry',
    tags: ['curry', 'seafood', 'spicy', 'coconut'],
    rating: 4.6,
    reviewCount: 1120,
    highlights: ['Curry', 'Thai', 'curry', 'seafood', 'spicy'],
  },
  {
    id: 11,
    slug: 'pesto-chicken-penne',
    name: 'Pesto Chicken Penne',
    description: 'Penne tossed with basil pesto, seared chicken, cherry tomatoes and toasted pine nuts.',
    longDescription: 'Toast pine nuts in a dry pan until golden â€” it only takes 2 minutes and adds incredible depth.',
    imgUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A bowl of pesto chicken penne with cherry tomatoes and basil',
    price: 72,
    category: 'Pasta',
    tags: ['pasta', 'chicken', 'pesto', 'quick'],
    rating: 4.5,
    reviewCount: 980,
    highlights: ['Pasta', 'Italian', 'pasta', 'chicken', 'pesto'],
  },
  {
    id: 12,
    slug: 'bbq-pulled-pork-bowl',
    name: 'BBQ Pulled Pork Bowl',
    description: 'Smoky pulled pork over fluffy rice with pickled slaw, corn and tangy BBQ drizzle.',
    longDescription: 'Quick-pickle the slaw with rice vinegar and a pinch of sugar â€” the acidity cuts through the richness perfectly.',
    imgUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A BBQ pulled pork bowl with rice, slaw and corn',
    price: 75,
    compareAtPrice: 83,
    category: 'Bowl',
    tags: ['bowl', 'pork', 'bbq', 'comfort'],
    rating: 4.6,
    reviewCount: 1450,
    highlights: ['Bowl', 'American', 'bowl', 'pork', 'bbq'],
  },
  {
    id: 13,
    slug: 'mango-chicken-salad',
    name: 'Mango Chicken Salad',
    description: 'Crisp greens with grilled chicken, ripe mango, avocado and citrus-chili dressing.',
    longDescription: 'Use a just-ripe mango â€” too soft and it falls apart, too firm and you miss the sweetness.',
    imgUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A fresh mango chicken salad with avocado and mixed greens',
    price: 78,
    category: 'Salad',
    tags: ['salad', 'chicken', 'mango', 'fresh'],
    rating: 4.3,
    reviewCount: 720,
    highlights: ['Salad', 'Fusion', 'salad', 'chicken', 'mango'],
  },
  {
    id: 14,
    slug: 'beef-teriyaki-stir-fry',
    name: 'Beef Teriyaki Stir-Fry',
    description: 'Tender beef strips glazed in homemade teriyaki with snap peas, peppers and steamed rice.',
    longDescription: 'Slice the beef against the grain and keep the pan screaming hot â€” this is how you get restaurant-quality sear at home.',
    imgUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Beef teriyaki stir-fry with vegetables and rice',
    price: 81,
    category: 'Stir-Fry',
    tags: ['stir-fry', 'beef', 'teriyaki', 'dinner'],
    rating: 4.7,
    reviewCount: 1890,
    highlights: ['Stir-Fry', 'Asian', 'stir-fry', 'beef', 'teriyaki'],
  },
  {
    id: 15,
    slug: 'red-lentil-coconut-curry',
    name: 'Red Lentil Coconut Curry',
    description: 'Velvety lentils simmered in spiced coconut milk with tomatoes and fresh cilantro.',
    longDescription: 'Red lentils break down naturally into a creamy texture â€” no blending needed. Stir occasionally to prevent sticking.',
    imgUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A warm bowl of red lentil curry with coconut cream swirl',
    price: 84,
    compareAtPrice: 92,
    category: 'Curry',
    tags: ['curry', 'vegan', 'lentils', 'comfort'],
    rating: 4.4,
    reviewCount: 1320,
    highlights: ['Curry', 'Fusion', 'curry', 'vegan', 'lentils'],
  },
  {
    id: 16,
    slug: 'ribeye-with-chimichurri',
    name: 'Ribeye with Chimichurri',
    description: 'Thick-cut ribeye with a bright herbaceous chimichurri and roasted fingerling potatoes.',
    longDescription: 'Make chimichurri ahead â€” the flavors meld and intensify after 30 minutes. Never skip the resting step for steak.',
    imgUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A grilled ribeye steak topped with fresh chimichurri sauce',
    price: 87,
    compareAtPrice: 99,
    category: 'Steak',
    tags: ['steak', 'grilled', 'herbs', 'dinner'],
    rating: 4.9,
    reviewCount: 2780,
    highlights: ['Steak', 'American', 'steak', 'grilled', 'herbs'],
  },
  {
    id: 17,
    slug: 'caprese-pasta-salad',
    name: 'Caprese Pasta Salad',
    description: 'Chilled fusilli with fresh mozzarella, ripe tomatoes, basil and balsamic glaze.',
    longDescription: 'Rinse pasta under cold water to stop cooking and keep it firm â€” this is the one time it is OK to do that.',
    imgUrl: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A colorful caprese pasta salad with tomatoes, mozzarella and basil',
    price: 90,
    category: 'Salad',
    tags: ['salad', 'pasta', 'vegetarian', 'summer'],
    rating: 4.2,
    reviewCount: 650,
    highlights: ['Salad', 'Italian', 'salad', 'pasta', 'vegetarian'],
  },
  {
    id: 18,
    slug: 'korean-bbq-beef-bowl',
    name: 'Korean BBQ Beef Bowl',
    description: 'Sweet-savory bulgogi beef over sticky rice with kimchi, pickled radish and a fried egg.',
    longDescription: 'A little grated Asian pear in the marinade tenderizes the beef and adds natural sweetness.',
    imgUrl: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A Korean BBQ beef bowl with kimchi, egg and pickled radish',
    price: 93,
    compareAtPrice: 101,
    category: 'Bowl',
    tags: ['bowl', 'beef', 'korean', 'umami'],
    rating: 4.8,
    reviewCount: 2140,
    highlights: ['Bowl', 'Asian', 'bowl', 'beef', 'korean'],
  },
  {
    id: 19,
    slug: 'crispy-fish-tacos',
    name: 'Crispy Fish Tacos',
    description: 'Beer-battered fish in warm tortillas with crunchy cabbage, lime crema and pickled jalapeÃ±o.',
    longDescription: 'Keep the oil at 180Â°C â€” too hot and the batter burns before the fish cooks through.',
    imgUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Crispy fish tacos with lime crema and purple cabbage slaw',
    price: 96,
    category: 'Main Course',
    tags: ['tacos', 'seafood', 'crispy', 'street-food'],
    rating: 4.5,
    reviewCount: 1670,
    highlights: ['Main Course', 'Fusion', 'tacos', 'seafood', 'crispy'],
  },
  {
    id: 20,
    slug: 'wild-mushroom-risotto',
    name: 'Wild Mushroom Risotto',
    description: 'Creamy arborio rice with a medley of wild mushrooms, white wine and aged parmesan.',
    longDescription: 'Never add cold broth â€” keep it warm beside the stove. Patience with stirring is what makes risotto silky.',
    imgUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A plate of creamy wild mushroom risotto with shaved parmesan',
    price: 99,
    category: 'Pasta',
    tags: ['risotto', 'mushroom', 'comfort', 'vegetarian'],
    rating: 4.6,
    reviewCount: 1560,
    highlights: ['Pasta', 'Italian', 'risotto', 'mushroom', 'comfort'],
  },
  {
    id: 21,
    slug: 'spicy-tuna-poke-bowl',
    name: 'Spicy Tuna Poke Bowl',
    description: 'Sushi-grade tuna over seasoned rice with cucumber, edamame, avocado and sriracha mayo.',
    longDescription: 'Keep tuna ice-cold until serving. Use the sharpest knife you have for clean, even cubes.',
    imgUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A vibrant spicy tuna poke bowl with avocado and edamame',
    price: 102,
    compareAtPrice: 110,
    category: 'Bowl',
    tags: ['bowl', 'tuna', 'raw', 'healthy'],
    rating: 4.4,
    reviewCount: 930,
    highlights: ['Bowl', 'Asian', 'bowl', 'tuna', 'raw'],
  },
  {
    id: 22,
    slug: 'lamb-kofta-platter',
    name: 'Lamb Kofta Platter',
    description: 'Spiced lamb skewers with warm flatbread, tzatziki, pickled onions and fresh herbs.',
    longDescription: 'Chill the kofta mixture for 30 minutes before shaping â€” cold fat holds its shape better on the grill.',
    imgUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A platter of lamb kofta skewers with tzatziki and flatbread',
    price: 105,
    category: 'Main Course',
    tags: ['lamb', 'grilled', 'mediterranean', 'dinner'],
    rating: 4.7,
    reviewCount: 1890,
    highlights: ['Main Course', 'Mediterranean', 'lamb', 'grilled', 'mediterranean'],
  },
  {
    id: 23,
    slug: 'shrimp-pad-thai',
    name: 'Shrimp Pad Thai',
    description: 'Rice noodles with plump shrimp, tamarind sauce, crushed peanuts and a squeeze of lime.',
    longDescription: 'Don\'t over-soak the noodles â€” they should be pliable but still firm. The wok finishes the cooking.',
    imgUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A plate of shrimp pad thai with peanuts and lime',
    price: 108,
    category: 'Stir-Fry',
    tags: ['noodles', 'shrimp', 'thai', 'street-food'],
    rating: 4.8,
    reviewCount: 2560,
    highlights: ['Stir-Fry', 'Thai', 'noodles', 'shrimp', 'thai'],
  },
  {
    id: 24,
    slug: 'grilled-chicken-caesar-salad',
    name: 'Grilled Chicken Caesar Salad',
    description: 'Charred chicken over crisp romaine with creamy caesar dressing, croutons and shaved parmesan.',
    longDescription: 'Grill the romaine for 30 seconds per side â€” the slight char adds smoky complexity to a classic salad.',
    imgUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A classic grilled chicken caesar salad with croutons and parmesan',
    price: 111,
    compareAtPrice: 119,
    category: 'Salad',
    tags: ['salad', 'chicken', 'classic', 'lunch'],
    rating: 4.3,
    reviewCount: 1150,
    highlights: ['Salad', 'American', 'salad', 'chicken', 'classic'],
  },
  {
    id: 25,
    slug: 'butter-chicken-masala',
    name: 'Butter Chicken Masala',
    description: 'Tender chicken in a silky tomato-butter sauce with warm spices and a touch of cream.',
    longDescription: 'The yogurt marinade is non-negotiable â€” it tenderizes the chicken and creates those charred edges.',
    imgUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A rich bowl of butter chicken masala with naan bread',
    price: 114,
    compareAtPrice: 126,
    category: 'Curry',
    tags: ['curry', 'chicken', 'creamy', 'spiced'],
    rating: 4.9,
    reviewCount: 3420,
    highlights: ['Curry', 'Fusion', 'curry', 'chicken', 'creamy'],
  },
  {
    id: 26,
    slug: 'pan-seared-salmon-fillet',
    name: 'Pan-Seared Salmon Fillet',
    description: 'Crispy-skinned salmon with lemon-dill sauce, roasted asparagus and herbed couscous.',
    longDescription: 'Start skin-side down in a cold pan with oil â€” this renders the fat slowly and gives you glass-like crispy skin.',
    imgUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A pan-seared salmon fillet with asparagus and lemon sauce',
    price: 117,
    category: 'Main Course',
    tags: ['salmon', 'seafood', 'healthy', 'elegant'],
    rating: 4.6,
    reviewCount: 1740,
    highlights: ['Main Course', 'Mediterranean', 'salmon', 'seafood', 'healthy'],
  },
  {
    id: 27,
    slug: 'chicken-tikka-skewers',
    name: 'Chicken Tikka Skewers',
    description: 'Yogurt-marinated chicken charred on skewers with mint chutney and warm naan.',
    longDescription: 'Soak wooden skewers in water for 30 minutes before grilling to prevent them from burning.',
    imgUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Charred chicken tikka skewers with mint chutney',
    price: 120,
    compareAtPrice: 128,
    category: 'Main Course',
    tags: ['chicken', 'grilled', 'spiced', 'skewers'],
    rating: 4.5,
    reviewCount: 1080,
    highlights: ['Main Course', 'Mediterranean', 'chicken', 'grilled', 'spiced'],
  },
  {
    id: 28,
    slug: 'tofu-veggie-stir-fry',
    name: 'Tofu Veggie Stir-Fry',
    description: 'Crispy pressed tofu with seasonal vegetables in a ginger-garlic sauce over jasmine rice.',
    longDescription: 'Press the tofu well â€” removing excess water is the single most important step for crispy tofu.',
    imgUrl: 'https://images.unsplash.com/photo-1607532941433-304659e8198a?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A colorful tofu and vegetable stir-fry over rice',
    price: 123,
    category: 'Stir-Fry',
    tags: ['tofu', 'vegan', 'stir-fry', 'healthy'],
    rating: 4.1,
    reviewCount: 480,
    highlights: ['Stir-Fry', 'Asian', 'tofu', 'vegan', 'stir-fry'],
  },
  {
    id: 29,
    slug: 'filet-mignon-red-wine-sauce',
    name: 'Filet Mignon with Red Wine Sauce',
    description: 'Butter-basted filet mignon with a rich red wine reduction and creamy mashed potatoes.',
    longDescription: 'Use a good drinking wine for the sauce â€” if you wouldn\'t drink it, don\'t cook with it.',
    imgUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A filet mignon steak with red wine sauce and mashed potatoes',
    price: 126,
    category: 'Steak',
    tags: ['steak', 'fine-dining', 'wine', 'special-occasion'],
    rating: 4.8,
    reviewCount: 2890,
    highlights: ['Steak', 'American', 'steak', 'fine-dining', 'wine'],
  },
  {
    id: 30,
    slug: 'coconut-chickpea-curry-bowl',
    name: 'Coconut Chickpea Curry Bowl',
    description: 'Spiced chickpeas in creamy coconut broth with spinach, sweet potato and toasted naan crumbles.',
    longDescription: 'Smash a few chickpeas against the side of the pot â€” it thickens the broth naturally without any flour.',
    imgUrl: 'https://images.unsplash.com/photo-1540914124281-342587941389?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'A warm coconut chickpea curry bowl with spinach and sweet potato',
    price: 129,
    compareAtPrice: 137,
    category: 'Bowl',
    tags: ['bowl', 'curry', 'vegan', 'chickpea'],
    rating: 4.4,
    reviewCount: 870,
    highlights: ['Bowl', 'Thai', 'bowl', 'curry', 'vegan'],
  },
];