import { CatalogSeedItem } from './catalog-seed-item.model';

export const CATALOG_SEED_DATA: CatalogSeedItem[] = [
  {
    id: 1,
    slug: 'anel-solitario-lumiere-oval',
    name: 'Anel Solitario Lumiere Oval',
    description: 'Anel em ouro amarelo 18k com zirconia oval central e aro delicado de brilho continuo.',
    longDescription: 'Peca de presenca elegante para pedido, presente marcante ou uso diario sofisticado. O desenho solitario valoriza a pedra central e combina com aparadores finos da mesma colecao.',
    imgUrl: 'jewelry-ring-solitaire.svg',
    imageAlt: 'Anel solitario dourado com pedra oval central e aro delicado',
    gallery: [
      { url: 'https://picsum.photos/600/600?lux1' },
      { url: 'https://picsum.photos/600/600?lux2' },
      { url: 'https://picsum.photos/600/600?lux3' },
      { url: 'https://picsum.photos/600/600?lux4' }
    ],
    price: 3890,
    compareAtPrice: 4290,
    category: 'Aneis',
    tags: ['anel', 'solitario', 'ouro-18k', 'zirconia-oval', 'lumiere', 'premium'],
    rating: 5,
    reviewCount: 184,
    highlights: ['Colecao Lumiere', 'Ouro 18k', 'Solitario', 'Premium', 'Best-seller'],
  },
  {
    id: 2,
    slug: 'colar-riviera-lumiere',
    name: 'Colar Riviera Lumiere',
    description: 'Colar riviera com fileira uniforme de zirconias e acabamento polido para ocasioes especiais.',
    longDescription: 'Modelo de brilho continuo que contorna o colo com caimento elegante e fecho seguro. Ideal para eventos, noivas e composicoes premium com brincos de ponto de luz.',
    imgUrl: 'jewelry-necklace-riviera.svg',
    imageAlt: 'Colar riviera com fileira continua de pedras claras e acabamento metalico',
    price: 5790,
    compareAtPrice: 6290,
    category: 'Colares',
    tags: ['colar', 'riviera', 'zirconia', 'ouro-branco', 'lumiere', 'noiva'],
    rating: 4.9,
    reviewCount: 126,
    highlights: ['Colecao Lumiere', 'Riviera', 'Ouro branco', 'Noiva', 'Premium'],
  },
  {
    id: 3,
    slug: 'conjunto-aura-gota',
    name: 'Conjunto Aura Gota',
    description: 'Conjunto com colar e brincos em formato de gota, pensado para festas e presentes memoraveis.',
    longDescription: 'A composicao entrega equilibrio entre brilho e leveza, com pedras em lapidacao gota e estrutura confortavel. Uma escolha pronta para eventos, madrinhas e datas comemorativas.',
    imgUrl: 'jewelry-set-harmony.svg',
    imageAlt: 'Conjunto de colar e brincos com pedras em formato de gota',
    price: 3890,
    compareAtPrice: 4290,
    category: 'Conjuntos',
    tags: ['conjunto', 'gota', 'presente', 'festa', 'aurora', 'zirconia'],
    rating: 4.8,
    reviewCount: 94,
    highlights: ['Colecao Aurora', 'Colar + brincos', 'Formato gota', 'Presente premium', 'Edicao festa'],
  },
  {
    id: 4,
    slug: 'alianca-essenza-lisa-3mm',
    name: 'Alianca Essenza Lisa 3mm',
    description: 'Alianca lisa de perfil confort em ouro amarelo 18k com espessura classica de 3mm.',
    longDescription: 'Modelo atemporal para compromisso ou uso diario, com polimento espelhado e interior anatomico. A largura de 3mm funciona bem para quem prefere uma joia discreta e elegante.',
    imgUrl: 'jewelry-bands-pair.svg',
    imageAlt: 'Aliancas lisas douradas com acabamento polido e perfil confort',
    price: 1490,
    category: 'Aliancas',
    tags: ['alianca', 'ouro-18k', 'lisa', 'compromisso', 'essenza', 'classica'],
    rating: 4.8,
    reviewCount: 211,
    highlights: ['Colecao Essenza', 'Ouro 18k', '3mm', 'Classica', 'Uso diario'],
  },
  {
    id: 5,
    slug: 'brinco-ponto-de-luz-lumiere',
    name: 'Brinco Ponto de Luz Lumiere',
    description: 'Brinco ponto de luz com pedra redonda e cravacao delicada para brilho cotidiano.',
    longDescription: 'Leve, facil de combinar e perfeito para primeiro furo ou composicoes minimalistas. O acabamento valoriza a pedra central sem excessos e traz a assinatura luminosa da colecao.',
    imgUrl: 'jewelry-earrings-studs.svg',
    imageAlt: 'Par de brincos pequenos com pedra redonda e brilho delicado',
    price: 1390,
    compareAtPrice: 1590,
    category: 'Brincos',
    tags: ['brinco', 'ponto-de-luz', 'zirconia', 'minimalista', 'lumiere', 'delicado'],
    rating: 4.9,
    reviewCount: 238,
    highlights: ['Colecao Lumiere', 'Ponto de luz', 'Delicado', 'Uso diario', 'Best-seller'],
  },
  {
    id: 6,
    slug: 'pulseira-tennis-lumiere',
    name: 'Pulseira Tennis Lumiere',
    description: 'Pulseira tennis com brilho linear e fecho seguro para composicoes de alto impacto.',
    longDescription: 'A fileira continua de pedras cria um visual refinado que funciona sozinha ou em mix com relogio e braceletes lisos. E uma peca premium para presentes e eventos.',
    imgUrl: 'jewelry-bracelet-tennis.svg',
    imageAlt: 'Pulseira tennis com sequencia continua de pedras claras e fecho joalheiro',
    price: 4890,
    compareAtPrice: 5290,
    category: 'Pulseiras',
    tags: ['pulseira', 'tennis', 'zirconia', 'lumiere', 'premium', 'festa'],
    rating: 4.9,
    reviewCount: 112,
    highlights: ['Colecao Lumiere', 'Pulseira tennis', 'Brilho continuo', 'Premium', 'Presente'],
  },
  {
    id: 7,
    slug: 'anel-aparador-aurora-pave',
    name: 'Anel Aparador Aurora Pave',
    description: 'Aparador pave com aro fino e microcravacao para combinar com solitarios e aneis lisos.',
    longDescription: 'Foi pensado para empilhar com joias de noivado ou usar sozinho em propostas mais discretas. O brilho delicado reforca a leitura premium sem pesar na composicao.',
    imgUrl: 'jewelry-ring-pave.svg',
    imageAlt: 'Anel fino com aro pave e brilho delicado em toda a frente',
    price: 1690,
    compareAtPrice: 1890,
    category: 'Aneis',
    tags: ['anel', 'aparador', 'pave', 'ouro-18k', 'aurora', 'stack'],
    rating: 4.7,
    reviewCount: 158,
    highlights: ['Colecao Aurora', 'Pave', 'Aro fino', 'Empilhavel', 'Novo'],
  },
  {
    id: 8,
    slug: 'choker-noite-aurea',
    name: 'Choker Noite Aurea',
    description: 'Choker de elos dourados com desenho fluido e presenca marcante para looks noturnos.',
    longDescription: 'A estrutura curta acompanha o colo com acabamento polido e proporcao elegante. Funciona muito bem sozinha ou com pingentes delicados em sobreposicao.',
    imgUrl: 'jewelry-necklace-chain.svg',
    imageAlt: 'Choker de elos dourados com acabamento polido e visual contemporaneo',
    price: 3290,
    compareAtPrice: 3590,
    category: 'Colares',
    tags: ['colar', 'choker', 'elos', 'ouro-amarelo', 'noite-aurea', 'statement'],
    rating: 4.7,
    reviewCount: 76,
    highlights: ['Colecao Noite Aurea', 'Choker', 'Elo dourado', 'Statement', 'Lancamento'],
  },
  {
    id: 9,
    slug: 'presente-duo-brilho',
    name: 'Presente Duo Brilho',
    description: 'Kit presente com brinco ponto de luz e pulseira delicada em embalagem pronta para surpreender.',
    longDescription: 'Foi montado para datas comemorativas com perfil de joia versatil: brilho suave, leitura feminina e combinacao facil com outros metais. Ja acompanha box premium do atelier.',
    imgUrl: 'jewelry-gift-box.svg',
    imageAlt: 'Caixa de presente premium com joias delicadas selecionadas',
    price: 1990,
    compareAtPrice: 2190,
    category: 'Presentes',
    tags: ['presente', 'kit', 'brilho', 'ponto-de-luz', 'pulseira', 'datas-especiais'],
    rating: 4.8,
    reviewCount: 143,
    highlights: ['Categoria Presentes', 'Kit pronto', 'Box premium', 'Presente facil', 'Edicao limitada'],
  },
  {
    id: 10,
    slug: 'anel-dueto-essenza',
    name: 'Anel Dueto Essenza',
    description: 'Anel com dois aros paralelos e acabamento polido para um visual contemporaneo e leve.',
    longDescription: 'O desenho dueto entrega a sensacao de composicao pronta, mas com conforto de peca unica. E indicado para quem gosta de aneis delicados com leitura moderna.',
    imgUrl: 'jewelry-ring-stack.svg',
    imageAlt: 'Anel com dois aros paralelos e acabamento polido',
    price: 2190,
    compareAtPrice: 2490,
    category: 'Aneis',
    tags: ['anel', 'dueto', 'stack', 'ouro-18k', 'essenza', 'contemporaneo'],
    rating: 4.6,
    reviewCount: 87,
    highlights: ['Colecao Essenza', 'Dois aros', 'Contemporaneo', 'Delicado', 'Novo'],
  },
  {
    id: 11,
    slug: 'anel-halo-celeste',
    name: 'Anel Halo Celeste',
    description: 'Anel halo com pedra central e contorno luminoso inspirado em joias classicas de festa.',
    longDescription: 'A cravacao ao redor da pedra amplia o brilho e cria uma presenca mais sofisticada no dedo. Ideal para quem busca um anel de impacto sem abrir mao da delicadeza.',
    imgUrl: 'jewelry-ring-solitaire.svg',
    imageAlt: 'Anel com pedra central e halo de brilho em volta',
    price: 4590,
    compareAtPrice: 4890,
    category: 'Aneis',
    tags: ['anel', 'halo', 'zirconia', 'festa', 'celeste', 'premium'],
    rating: 4.8,
    reviewCount: 69,
    highlights: ['Colecao Celeste', 'Halo', 'Pedra central', 'Festa', 'Premium'],
  },
  {
    id: 12,
    slug: 'par-de-aliancas-essenza-classic-4mm',
    name: 'Par de Aliancas Essenza Classic 4mm',
    description: 'Par de aliancas confort 4mm com acabamento liso e proporcao equilibrada para casais.',
    longDescription: 'As duas pecas seguem o mesmo desenho classico com interior anatomico e brilho espelhado. Uma escolha segura para noivado, casamento civil ou renovacao de votos.',
    imgUrl: 'jewelry-bands-pair.svg',
    imageAlt: 'Par de aliancas lisas com largura media e acabamento espelhado',
    price: 3190,
    compareAtPrice: 3490,
    category: 'Aliancas',
    tags: ['alianca', 'par', '4mm', 'essenza', 'casamento', 'confort'],
    rating: 4.9,
    reviewCount: 173,
    highlights: ['Colecao Essenza', 'Par de aliancas', '4mm', 'Confort', 'Best-seller'],
  },
  {
    id: 13,
    slug: 'alianca-verona-fosca-5mm',
    name: 'Alianca Verona Fosca 5mm',
    description: 'Alianca fosca com bordas polidas e leitura contemporanea para quem prefere sobriedade.',
    longDescription: 'O contraste entre centro escovado e laterais brilhantes cria profundidade sem excessos. A largura de 5mm traz presenca elegante e confortavel para o uso diario.',
    imgUrl: 'jewelry-bands-pair.svg',
    imageAlt: 'Alianca de acabamento fosco com bordas polidas',
    price: 1890,
    category: 'Aliancas',
    tags: ['alianca', 'fosca', '5mm', 'verona', 'compromisso', 'moderna'],
    rating: 4.7,
    reviewCount: 102,
    highlights: ['Colecao Verona', 'Acabamento fosco', '5mm', 'Contemporanea', 'Uso diario'],
  },
  {
    id: 14,
    slug: 'alianca-verona-friso-diamantado-6mm',
    name: 'Alianca Verona Friso Diamantado 6mm',
    description: 'Alianca 6mm com friso diamantado e acabamento premium para um brilho discreto e sofisticado.',
    longDescription: 'O friso central entrega textura refinada e valoriza a largura maior da peca. E indicada para clientes que buscam aliancas marcantes sem abrir mao da elegancia classica.',
    imgUrl: 'jewelry-bands-pair.svg',
    imageAlt: 'Alianca larga com friso central texturizado e brilho discreto',
    price: 2290,
    compareAtPrice: 2490,
    category: 'Aliancas',
    tags: ['alianca', 'friso', '6mm', 'verona', 'premium', 'compromisso'],
    rating: 4.8,
    reviewCount: 91,
    highlights: ['Colecao Verona', 'Friso diamantado', '6mm', 'Premium', 'Compromisso'],
  },
  {
    id: 15,
    slug: 'colar-gota-celeste',
    name: 'Colar Gota Celeste',
    description: 'Colar delicado com pingente gota e banho luminoso para uso diario com toque feminino.',
    longDescription: 'A proporcao do pingente favorece sobreposicoes, enquanto a pedra lapidada traz luz na medida certa. Funciona muito bem como presente romantico e joia de entrada premium.',
    imgUrl: 'jewelry-necklace-drop.svg',
    imageAlt: 'Colar delicado com pingente em formato de gota e pedra clara',
    price: 2190,
    compareAtPrice: 2390,
    category: 'Colares',
    tags: ['colar', 'gota', 'delicado', 'celeste', 'presente', 'ouro-18k'],
    rating: 4.7,
    reviewCount: 164,
    highlights: ['Colecao Celeste', 'Pingente gota', 'Delicado', 'Presente', 'Uso diario'],
  },
  {
    id: 16,
    slug: 'colar-elo-atelier',
    name: 'Colar Elo Atelier',
    description: 'Colar de elos alongados com desenho limpo e acabamento polido para compor mixes modernos.',
    longDescription: 'O caimento leve e o fecho ajustavel permitem usar a peca sozinha ou em camadas com pingentes. E uma base elegante para quem gosta de joalheria contemporanea.',
    imgUrl: 'jewelry-necklace-chain.svg',
    imageAlt: 'Colar de elos alongados com acabamento polido e fecho ajustavel',
    price: 1690,
    category: 'Colares',
    tags: ['colar', 'elos', 'ajustavel', 'atelier', 'moderno', 'ouro-amarelo'],
    rating: 4.6,
    reviewCount: 117,
    highlights: ['Colecao Atelier', 'Elo alongado', 'Ajustavel', 'Contemporaneo', 'Versatil'],
  },
  {
    id: 17,
    slug: 'brinco-gota-celeste',
    name: 'Brinco Gota Celeste',
    description: 'Brinco pequeno em formato de gota com brilho pontual e leitura sofisticada.',
    longDescription: 'O desenho acompanha o rosto com leveza e entrega um visual refinado para o dia ou noite. Combina com colares da mesma colecao e com penteados presos.',
    imgUrl: 'jewelry-earrings-drop.svg',
    imageAlt: 'Par de brincos pequenos em formato de gota com pedra clara',
    price: 1790,
    compareAtPrice: 1990,
    category: 'Brincos',
    tags: ['brinco', 'gota', 'celeste', 'zirconia', 'festa', 'delicado'],
    rating: 4.8,
    reviewCount: 109,
    highlights: ['Colecao Celeste', 'Formato gota', 'Brilho suave', 'Festa', 'Delicado'],
  },
  {
    id: 18,
    slug: 'brinco-argola-verona-media',
    name: 'Brinco Argola Verona Media',
    description: 'Argola media com perfil polido e fecho seguro para uma joia curinga de closet.',
    longDescription: 'Tem tamanho equilibrado para acompanhar producoes casuais e noturnas, sem perder conforto. A leitura e classica, mas o acabamento espelhado deixa a peca mais atual.',
    imgUrl: 'jewelry-earrings-hoops.svg',
    imageAlt: 'Par de argolas medias com acabamento polido',
    price: 1590,
    category: 'Brincos',
    tags: ['brinco', 'argola', 'verona', 'media', 'classico', 'ouro-18k'],
    rating: 4.7,
    reviewCount: 193,
    highlights: ['Colecao Verona', 'Argola media', 'Classica', 'Uso diario', 'Best-seller'],
  },
  {
    id: 19,
    slug: 'brinco-argola-aurora-pave',
    name: 'Brinco Argola Aurora Pave',
    description: 'Argola com frente pave e brilho continuo para looks de festa e producoes elegantes.',
    longDescription: 'A pedra frontal valoriza o movimento da argola sem comprometer o conforto. E uma proposta refinada para quem gosta de joias com mais presenca visual.',
    imgUrl: 'jewelry-earrings-hoops.svg',
    imageAlt: 'Par de argolas com frente pave e acabamento brilhante',
    price: 2390,
    compareAtPrice: 2690,
    category: 'Brincos',
    tags: ['brinco', 'argola', 'pave', 'aurora', 'festa', 'premium'],
    rating: 4.8,
    reviewCount: 88,
    highlights: ['Colecao Aurora', 'Argola pave', 'Brilho continuo', 'Festa', 'Premium'],
  },
  {
    id: 20,
    slug: 'pulseira-elo-seda',
    name: 'Pulseira Elo Seda',
    description: 'Pulseira de elos finos com toque macio e acabamento polido para pulso delicado.',
    longDescription: 'A trama leve permite uso continuo e combinacoes com relogio ou outras pulseiras finas. E uma joia versatil para presente e composicoes minimalistas.',
    imgUrl: 'jewelry-bracelet-chain.svg',
    imageAlt: 'Pulseira de elos finos com acabamento polido',
    price: 1490,
    category: 'Pulseiras',
    tags: ['pulseira', 'elos', 'delicada', 'atelier', 'presente', 'ouro-18k'],
    rating: 4.6,
    reviewCount: 131,
    highlights: ['Colecao Atelier', 'Elo fino', 'Delicada', 'Versatil', 'Presente'],
  },
  {
    id: 21,
    slug: 'pulseira-celeste-regulavel',
    name: 'Pulseira Celeste Regulavel',
    description: 'Pulseira regulavel com ponto de brilho central e proposta delicada para o dia a dia.',
    longDescription: 'O ajuste por extensor facilita o presente e melhora o caimento em diferentes pulsos. A pedra central conversa com aneis e brincos leves da linha Celeste.',
    imgUrl: 'jewelry-bracelet-chain.svg',
    imageAlt: 'Pulseira regulavel com detalhe central de brilho',
    price: 1290,
    compareAtPrice: 1450,
    category: 'Pulseiras',
    tags: ['pulseira', 'regulavel', 'celeste', 'delicada', 'zirconia', 'presente'],
    rating: 4.7,
    reviewCount: 148,
    highlights: ['Colecao Celeste', 'Regulavel', 'Ponto de brilho', 'Delicada', 'Uso diario'],
  },
  {
    id: 22,
    slug: 'pulseira-riviera-essenza',
    name: 'Pulseira Riviera Essenza',
    description: 'Pulseira riviera mais enxuta, pensada para clientes que buscam brilho premium com leitura leve.',
    longDescription: 'Entrega o efeito classico da riviera em uma proporcao facil de usar sozinha ou em composicoes. O fecho reforcado garante seguranca para ocasioes especiais.',
    imgUrl: 'jewelry-bracelet-tennis.svg',
    imageAlt: 'Pulseira riviera delicada com fileira de pedras claras',
    price: 2690,
    compareAtPrice: 2990,
    category: 'Pulseiras',
    tags: ['pulseira', 'riviera', 'essenza', 'zirconia', 'premium', 'festa'],
    rating: 4.8,
    reviewCount: 97,
    highlights: ['Colecao Essenza', 'Riviera delicada', 'Brilho premium', 'Festa', 'Presente'],
  },
  {
    id: 23,
    slug: 'pingente-medalha-poema',
    name: 'Pingente Medalha Poema',
    description: 'Pingente medalha com acabamento espelhado para gravacao ou uso minimalista.',
    longDescription: 'E uma joia afetiva, pensada para presentes de aniversario, maternidade ou datas simbolicas. A superficie lisa permite personalizacao futura e combina com correntes finas do atelier.',
    imgUrl: 'jewelry-pendant-medal.svg',
    imageAlt: 'Pingente medalha redondo com acabamento polido',
    price: 990,
    category: 'Pingentes',
    tags: ['pingente', 'medalha', 'poema', 'gravacao', 'presente', 'minimalista'],
    rating: 4.7,
    reviewCount: 122,
    highlights: ['Colecao Poema', 'Medalha lisa', 'Personalizavel', 'Presente afetivo', 'Delicado'],
  },
  {
    id: 24,
    slug: 'pingente-inicial-aurora',
    name: 'Pingente Inicial Aurora',
    description: 'Pingente de inicial com acabamento polido para compor colares personalizados e presentes autorais.',
    longDescription: 'A escala pequena funciona sozinha ou em duplas, permitindo montar narrativas afetivas no colo. E uma das pecas mais procuradas para presentear com significado.',
    imgUrl: 'jewelry-pendant-charm.svg',
    imageAlt: 'Pingente pequeno em formato de letra com acabamento polido',
    price: 890,
    compareAtPrice: 990,
    category: 'Pingentes',
    tags: ['pingente', 'inicial', 'aurora', 'personalizado', 'presente', 'delicado'],
    rating: 4.8,
    reviewCount: 205,
    highlights: ['Colecao Aurora', 'Inicial', 'Personalizado', 'Presente', 'Best-seller'],
  },
  {
    id: 25,
    slug: 'pingente-coracao-essenza',
    name: 'Pingente Coracao Essenza',
    description: 'Pingente coracao com contorno suave e brilho discreto para joias romanticas de uso diario.',
    longDescription: 'O desenho foge do excesso e mantem uma leitura sofisticada, ideal para quem prefere simbolos afetivos mais elegantes. Funciona muito bem com correntes curtas e medias.',
    imgUrl: 'jewelry-pendant-charm.svg',
    imageAlt: 'Pingente em formato de coracao com acabamento polido',
    price: 1290,
    compareAtPrice: 1490,
    category: 'Pingentes',
    tags: ['pingente', 'coracao', 'essenza', 'romantico', 'presente', 'ouro-18k'],
    rating: 4.6,
    reviewCount: 84,
    highlights: ['Colecao Essenza', 'Coracao', 'Romantico', 'Uso diario', 'Presente'],
  },
  {
    id: 26,
    slug: 'pingente-trevo-celeste',
    name: 'Pingente Trevo Celeste',
    description: 'Pingente trevo de quatro folhas com brilho leve e proposta de amuleto contemporaneo.',
    longDescription: 'A silhueta simbolica ganha acabamento refinado e combina com correntes delicadas do atelier. E uma opcao charmosa para presente com narrativa de sorte e protecao.',
    imgUrl: 'jewelry-pendant-charm.svg',
    imageAlt: 'Pingente de trevo delicado com acabamento polido',
    price: 1190,
    category: 'Pingentes',
    tags: ['pingente', 'trevo', 'celeste', 'amuleto', 'presente', 'delicado'],
    rating: 4.7,
    reviewCount: 93,
    highlights: ['Colecao Celeste', 'Trevo', 'Amuleto', 'Presente', 'Delicado'],
  },
  {
    id: 27,
    slug: 'conjunto-verona-classico',
    name: 'Conjunto Verona Classico',
    description: 'Conjunto com colar de elo curto e argolas medias para uma combinacao pronta e versatil.',
    longDescription: 'Pensado para clientes que desejam uma compra segura e facil de usar, ele equilibra presenca, conforto e leitura classica. O acabamento polido valoriza o metal em todas as pecas.',
    imgUrl: 'jewelry-set-harmony.svg',
    imageAlt: 'Conjunto com colar curto e argolas de tamanho medio',
    price: 4590,
    compareAtPrice: 4990,
    category: 'Conjuntos',
    tags: ['conjunto', 'verona', 'colar', 'argola', 'classico', 'presente'],
    rating: 4.8,
    reviewCount: 71,
    highlights: ['Colecao Verona', 'Mix pronto', 'Colar + argolas', 'Classico', 'Presente premium'],
  },
  {
    id: 28,
    slug: 'conjunto-lumiere-noiva',
    name: 'Conjunto Lumiere Noiva',
    description: 'Conjunto premium com colar riviera e brincos de brilho linear para casamentos e eventos formais.',
    longDescription: 'Foi pensado para noivas e madrinhas que buscam impacto elegante, com pedras alinhadas e acabamento impecavel. A leitura e sofisticada e fotogenica, sem competir com o vestido.',
    imgUrl: 'jewelry-set-harmony.svg',
    imageAlt: 'Conjunto premium com colar e brincos de brilho continuo',
    price: 6890,
    compareAtPrice: 7390,
    category: 'Conjuntos',
    tags: ['conjunto', 'lumiere', 'noiva', 'riviera', 'premium', 'evento'],
    rating: 5,
    reviewCount: 52,
    highlights: ['Colecao Lumiere', 'Noiva', 'Riviera', 'Premium', 'Edicao cerimonia'],
  },
  {
    id: 29,
    slug: 'presente-medalha-e-corrente-poema',
    name: 'Presente Medalha e Corrente Poema',
    description: 'Kit com corrente delicada e medalha lisa para presentes com apelo afetivo e personalizacao futura.',
    longDescription: 'A combinacao nasce pronta para embalar datas especiais e deixa espaco para gravacao posterior. E uma curadoria segura para aniversario, bodas ou lembrancas de familia.',
    imgUrl: 'jewelry-gift-box.svg',
    imageAlt: 'Kit presente com corrente fina e medalha lisa dentro de box premium',
    price: 1590,
    compareAtPrice: 1790,
    category: 'Presentes',
    tags: ['presente', 'kit', 'medalha', 'corrente', 'poema', 'datas-especiais'],
    rating: 4.7,
    reviewCount: 118,
    highlights: ['Categoria Presentes', 'Corrente + medalha', 'Personalizavel', 'Presente afetivo', 'Box premium'],
  },
  {
    id: 30,
    slug: 'presente-aurora-celebration',
    name: 'Presente Aurora Celebration',
    description: 'Selecao de anel delicado e brinco de brilho suave em box premium para surpreender com elegancia.',
    longDescription: 'Curadoria pensada para quem quer presentear sem erro, reunindo duas pecas versateis e femininas. O conjunto chega pronto para entrega e conversa com diferentes estilos.',
    imgUrl: 'jewelry-gift-box.svg',
    imageAlt: 'Box premium com anel delicado e brinco de brilho suave',
    price: 3490,
    compareAtPrice: 3790,
    category: 'Presentes',
    tags: ['presente', 'anel', 'brinco', 'aurora', 'box-premium', 'celebration'],
    rating: 4.8,
    reviewCount: 67,
    highlights: ['Categoria Presentes', 'Anel + brinco', 'Curadoria premium', 'Entrega pronta', 'Edicao comemorativa'],
  },
];
