import { RecipeModel } from './models';

export const MOCK_RECIPES: RecipeModel[] = [
    {
        id: 1,
        slug: 'lemon-garlic-shrimp-pasta',
        name: 'Lemon-Garlic Shrimp Pasta',
        description: 'Silky garlic butter pasta tossed with shrimp, lemon zest and fresh herbs.',
        imgUrl: 'https://images.unsplash.com/photo-1762631178604-3b79d4d0bff9?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A plate of lemon-garlic shrimp pasta garnished with parsley',
        isFavorite: true,
        category: 'Pasta',
        cuisine: 'Italian',
        tags: ['seafood', 'pasta', 'quick', 'garlic'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 15,
        calories: 520,
        ingredients: [
            { id: 101, name: 'Shrimp', quantity: 250, unit: 'g' },
            { id: 102, name: 'Lemon', quantity: 1, unit: 'each' },
            { id: 103, name: 'Pasta', quantity: 250, unit: 'g' },
            { id: 104, name: 'Garlic', quantity: 2, unit: 'cloves' },
            { id: 105, name: 'Parsley', quantity: 2, unit: 'tbsp' },
        ],
        durationMinutes: 25,
        difficulty: 'Easy',
        rating: 4.8,
        reviewCount: 1240,
        steps: [
            'Cook pasta according to package directions until al dente. Drain and reserve ½ cup pasta water.',
            'Sauté shrimp in olive oil and garlic butter until pink, about 2–3 minutes per side. Remove and set aside.',
            'Combine pasta with lemon juice, zest, reserved water and shrimp. Toss until silky and well coated.',
        ],
        tips: 'Use fresh lemon juice and zest for the brightest flavor. Pull shrimp off heat when just pink — they continue cooking from residual heat.',
        featured: false,
    },
    {
        id: 2,
        slug: 'mediterranean-quinoa-salad',
        name: 'Mediterranean Quinoa Salad',
        description: 'A bright grain salad with cucumber, tomato, herbs and creamy feta.',
        imgUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A colorful quinoa salad bowl with feta, tomatoes and cucumber',
        isFavorite: true,
        category: 'Salad',
        cuisine: 'Mediterranean',
        tags: ['salad', 'healthy', 'vegetarian', 'meal-prep'],
        servings: 4,
        prepMinutes: 15,
        cookMinutes: 15,
        calories: 340,
        ingredients: [
            { id: 201, name: 'Quinoa', quantity: 180, unit: 'g' },
            { id: 202, name: 'Tomatoes', quantity: 150, unit: 'g' },
            { id: 203, name: 'Cucumber', quantity: 1, unit: 'each' },
            { id: 204, name: 'Feta', quantity: 60, unit: 'g' },
        ],
        durationMinutes: 30,
        difficulty: 'Easy',
        rating: 4.5,
        reviewCount: 870,
        steps: [
            'Rinse and cook quinoa in salted water until fluffy. Spread on a tray to cool.',
            'Dice tomatoes, cucumber and red onion. Crumble feta cheese.',
            'Toss everything with olive oil, lemon juice, salt and fresh herbs.',
        ],
        tips: 'Make ahead and refrigerate — the flavors develop and get even better overnight.',
        featured: false,
    },
    {
        id: 3,
        slug: 'roasted-veggie-buddha-bowl',
        name: 'Roasted Veggie Buddha Bowl',
        description: 'Oven-roasted vegetables, grains and creamy dressing in a hearty bowl.',
        imgUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A hearty buddha bowl with roasted sweet potato, broccoli, chickpeas and tahini',
        isFavorite: true,
        category: 'Bowl',
        cuisine: 'Fusion',
        tags: ['bowl', 'vegan', 'roasted', 'healthy'],
        servings: 2,
        prepMinutes: 15,
        cookMinutes: 30,
        calories: 480,
        ingredients: [
            { id: 301, name: 'Broccoli', quantity: 180, unit: 'g' },
            { id: 302, name: 'Sweet potato', quantity: 250, unit: 'g' },
            { id: 303, name: 'Rice', quantity: 180, unit: 'g' },
            { id: 304, name: 'Chickpeas', quantity: 150, unit: 'g' },
            { id: 305, name: 'Tahini', quantity: 2, unit: 'tbsp' },
        ],
        durationMinutes: 45,
        difficulty: 'Medium',
        rating: 4.7,
        reviewCount: 1560,
        steps: [
            'Preheat oven to 200°C. Toss sweet potato and broccoli with oil, salt and spices.',
            'Roast vegetables for 25–30 minutes until golden and tender.',
            'Assemble bowls with rice, roasted vegetables, chickpeas and tahini drizzle.',
        ],
        tips: 'Massage kale with a little oil and salt if adding greens — it softens the texture beautifully.',
        featured: false,
    },
    {
        id: 4,
        slug: 'new-york-strip-steak',
        name: 'New York Strip Steak',
        description: 'Seared steakhouse-style with buttered green beans and pan sauce.',
        imgUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A perfectly seared New York strip steak with green beans',
        isFavorite: false,
        category: 'Steak',
        cuisine: 'American',
        tags: ['steak', 'dinner', 'cast-iron', 'protein'],
        servings: 1,
        prepMinutes: 5,
        cookMinutes: 15,
        calories: 650,
        ingredients: [
            { id: 401, name: 'Steak', quantity: 1, unit: 'each' },
            { id: 402, name: 'Green beans', quantity: 180, unit: 'g' },
            { id: 403, name: 'Butter', quantity: 1, unit: 'tbsp' },
            { id: 404, name: 'Garlic', quantity: 2, unit: 'cloves' },
            { id: 405, name: 'Rosemary', quantity: 1, unit: 'sprig' },
        ],
        durationMinutes: 20,
        difficulty: 'Hard',
        rating: 4.9,
        reviewCount: 3180,
        steps: [
            'Bring steak to room temperature. Season generously with salt and pepper.',
            'Sear in a hot cast-iron skillet with oil for 3–4 minutes each side. Add butter, garlic and rosemary to baste.',
            'Rest steak for 5 minutes before slicing. Serve with buttered green beans.',
        ],
        tips: 'Let the steak rest — this redistributes juices for a more tender, flavorful bite.',
        featured: false,
    },
    {
        id: 5,
        slug: 'thai-green-curry-chicken',
        name: 'Thai Green Curry Chicken',
        description: 'Creamy coconut curry with chicken, herbs and bright green vegetables.',
        imgUrl: 'https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A bowl of Thai green curry chicken with basil and coconut cream',
        isFavorite: false,
        category: 'Curry',
        cuisine: 'Thai',
        tags: ['curry', 'chicken', 'spicy', 'coconut'],
        servings: 3,
        prepMinutes: 10,
        cookMinutes: 25,
        calories: 560,
        ingredients: [
            { id: 501, name: 'Chicken', quantity: 250, unit: 'g' },
            { id: 502, name: 'Coconut milk', quantity: 400, unit: 'ml' },
            { id: 503, name: 'Green curry paste', quantity: 2, unit: 'tbsp' },
            { id: 504, name: 'Basil', quantity: 1, unit: 'handful' },
            { id: 505, name: 'Rice', quantity: 180, unit: 'g' },
        ],
        durationMinutes: 35,
        difficulty: 'Medium',
        rating: 4.6,
        reviewCount: 2010,
        steps: [
            'Slice chicken and vegetables. Heat oil in a deep pan over medium-high heat.',
            'Fry curry paste for 1 minute, then add coconut milk and bring to a simmer.',
            'Add chicken and vegetables. Cook until done and sauce thickens. Finish with fresh basil.',
        ],
        tips: 'Toast the curry paste in oil before adding coconut milk — it deepens the flavor significantly.',
        featured: false,
    },
    {
        id: 6,
        slug: 'sesame-chicken-rice-bowl',
        name: 'Sesame Chicken Rice Bowl',
        description: 'A warm bowl layered with roasted vegetables, fluffy rice and tender sesame-glazed chicken.',
        imgUrl: 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A sesame chicken rice bowl with broccoli and carrots',
        isFavorite: true,
        category: 'Bowl',
        cuisine: 'Asian',
        tags: ['bowl', 'chicken', 'sesame', 'rice'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 20,
        calories: 490,
        ingredients: [
            { id: 601, name: 'Chicken', quantity: 200, unit: 'g' },
            { id: 602, name: 'Broccoli', quantity: 150, unit: 'g' },
            { id: 603, name: 'Rice', quantity: 180, unit: 'g' },
            { id: 604, name: 'Carrot', quantity: 1, unit: 'each' },
            { id: 605, name: 'Sesame', quantity: 1, unit: 'tbsp' },
        ],
        durationMinutes: 30,
        difficulty: 'Easy',
        rating: 4.3,
        reviewCount: 640,
        steps: [
            'Cook rice according to package directions. Steam broccoli and slice carrot into rounds.',
            'Season chicken with soy sauce, sesame oil and a pinch of sugar. Sear in a hot pan until golden.',
            'Slice chicken and assemble bowls with rice, vegetables and a drizzle of sesame sauce.',
        ],
        tips: 'Toast the sesame seeds in a dry pan for 1 minute to unlock their nutty aroma.',
        featured: false,
    },
    {
        id: 7,
        slug: 'roasted-veggie-stir-fry-noodles',
        name: 'Roasted Veggie Stir-Fry Noodles',
        description: 'Pan-finished noodles with colorful roasted vegetables and savory soy-ginger sauce.',
        imgUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A plate of stir-fry noodles with roasted vegetables and mushrooms',
        isFavorite: false,
        category: 'Stir-Fry',
        cuisine: 'Asian',
        tags: ['noodles', 'vegetarian', 'stir-fry', 'quick'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 15,
        calories: 410,
        ingredients: [
            { id: 701, name: 'Pasta', quantity: 220, unit: 'g' },
            { id: 702, name: 'Broccoli', quantity: 120, unit: 'g' },
            { id: 703, name: 'Bell pepper', quantity: 1, unit: 'each' },
            { id: 704, name: 'Mushrooms', quantity: 150, unit: 'g' },
            { id: 705, name: 'Soy sauce', quantity: 2, unit: 'tbsp' },
        ],
        durationMinutes: 25,
        difficulty: 'Easy',
        rating: 4.4,
        reviewCount: 1780,
        steps: [
            'Cook noodles until just under al dente. Drain and toss with a splash of sesame oil.',
            'Stir-fry broccoli, bell pepper and mushrooms over high heat for 3–4 minutes.',
            'Add noodles and soy sauce to the pan. Toss until everything is coated and slightly charred.',
        ],
        tips: 'High heat is key — it gives the noodles that slightly smoky wok flavor even in a regular pan.',
        featured: false,
    },
    {
        id: 8,
        slug: 'herb-basted-skillet-chicken',
        name: 'Herb-Basted Skillet Chicken',
        description: 'Juicy skillet chicken basted in herb butter, served with crispy potatoes and roasted broccoli.',
        imgUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'Herb-basted chicken in a cast-iron skillet with potatoes',
        isFavorite: false,
        category: 'Main Course',
        cuisine: 'American',
        tags: ['chicken', 'skillet', 'comfort', 'one-pan'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 40,
        calories: 580,
        ingredients: [
            { id: 801, name: 'Chicken', quantity: 220, unit: 'g' },
            { id: 802, name: 'Potatoes', quantity: 250, unit: 'g' },
            { id: 803, name: 'Garlic', quantity: 2, unit: 'cloves' },
            { id: 804, name: 'Broccoli', quantity: 140, unit: 'g' },
            { id: 805, name: 'Butter', quantity: 1, unit: 'tbsp' },
        ],
        durationMinutes: 50,
        difficulty: 'Medium',
        rating: 4.7,
        reviewCount: 2350,
        steps: [
            'Preheat oven to 200°C. Season chicken generously with salt, pepper and dried herbs.',
            'Sear chicken skin-side down in a hot skillet for 5 minutes. Flip and add potatoes, garlic and butter.',
            'Transfer skillet to oven and roast for 25–30 minutes. Add broccoli in the last 10 minutes.',
            'Baste chicken with pan juices before serving.',
        ],
        tips: 'Pat the chicken dry before searing — moisture is the enemy of a crispy golden skin.',
        featured: true,
    },
    {
        id: 9,
        slug: 'creamy-tuscan-chicken-pasta',
        name: 'Creamy Tuscan Chicken Pasta',
        description: 'Creamy pasta with seared chicken, sun-dried tomatoes, spinach and a rich garlic parmesan finish.',
        imgUrl: 'https://images.unsplash.com/photo-1724116382285-f4fcbe27f6a1?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'Creamy Tuscan chicken pasta with spinach and parmesan',
        isFavorite: false,
        category: 'Pasta',
        cuisine: 'Italian',
        tags: ['pasta', 'chicken', 'creamy', 'comfort'],
        servings: 3,
        prepMinutes: 10,
        cookMinutes: 20,
        calories: 620,
        ingredients: [
            { id: 901, name: 'Chicken', quantity: 200, unit: 'g' },
            { id: 902, name: 'Pasta', quantity: 220, unit: 'g' },
            { id: 903, name: 'Cream', quantity: 200, unit: 'ml' },
            { id: 904, name: 'Parmesan', quantity: 60, unit: 'g' },
            { id: 905, name: 'Spinach', quantity: 80, unit: 'g' },
        ],
        durationMinutes: 30,
        difficulty: 'Easy',
        rating: 4.2,
        reviewCount: 540,
        steps: [
            'Cook pasta until al dente. Meanwhile, season and sear chicken until golden on both sides.',
            'Remove chicken and deglaze pan with garlic and cream. Stir in parmesan until melted.',
            'Add spinach and let it wilt. Slice chicken, toss with pasta and sauce.',
        ],
        tips: 'Deglaze the pan after searing the chicken — those brown bits are pure flavor.',
        featured: false,
    },
    {
        id: 10,
        slug: 'thai-coconut-shrimp-curry',
        name: 'Thai Coconut Shrimp Curry',
        description: 'Fragrant curry broth with shrimp, basil, lime and silky coconut richness.',
        imgUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A fragrant Thai coconut shrimp curry with lime and basil',
        isFavorite: true,
        category: 'Curry',
        cuisine: 'Thai',
        tags: ['curry', 'seafood', 'spicy', 'coconut'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 20,
        calories: 470,
        ingredients: [
            { id: 1001, name: 'Shrimp', quantity: 250, unit: 'g' },
            { id: 1002, name: 'Coconut milk', quantity: 350, unit: 'ml' },
            { id: 1003, name: 'Basil', quantity: 1, unit: 'handful' },
            { id: 1004, name: 'Lime', quantity: 1, unit: 'each' },
            { id: 1005, name: 'Rice', quantity: 180, unit: 'g' },
        ],
        durationMinutes: 30,
        difficulty: 'Hard',
        rating: 4.6,
        reviewCount: 1120,
        steps: [
            'Prepare shrimp: peel, devein and pat dry. Mince garlic and slice chili.',
            'Sauté garlic and chili in oil. Add coconut milk, fish sauce and lime leaves. Simmer for 5 minutes.',
            'Add shrimp and cook until pink, about 3 minutes. Finish with fresh basil and a squeeze of lime.',
        ],
        tips: 'Add the shrimp at the very end — overcooking makes them rubbery. Serve with steamed jasmine rice.',
        featured: false,
    },
    {
        id: 11,
        slug: 'pesto-chicken-penne',
        name: 'Pesto Chicken Penne',
        description: 'Penne tossed with basil pesto, seared chicken, cherry tomatoes and toasted pine nuts.',
        imgUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A bowl of pesto chicken penne with cherry tomatoes and basil',
        isFavorite: false,
        category: 'Pasta',
        cuisine: 'Italian',
        tags: ['pasta', 'chicken', 'pesto', 'quick'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 15,
        calories: 540,
        ingredients: [
            { id: 1101, name: 'Penne', quantity: 250, unit: 'g' },
            { id: 1102, name: 'Chicken breast', quantity: 200, unit: 'g' },
            { id: 1103, name: 'Basil pesto', quantity: 3, unit: 'tbsp' },
            { id: 1104, name: 'Cherry tomatoes', quantity: 150, unit: 'g' },
            { id: 1105, name: 'Pine nuts', quantity: 2, unit: 'tbsp' },
        ],
        durationMinutes: 25,
        difficulty: 'Easy',
        rating: 4.5,
        reviewCount: 980,
        steps: [
            'Cook penne in salted water until al dente. Reserve ½ cup pasta water before draining.',
            'Season and sear chicken breast until golden, about 5 minutes per side. Slice into strips.',
            'Toss pasta with pesto, halved tomatoes, chicken and a splash of pasta water. Top with pine nuts.',
        ],
        tips: 'Toast pine nuts in a dry pan until golden — it only takes 2 minutes and adds incredible depth.',
        featured: false,
    },
    {
        id: 12,
        slug: 'bbq-pulled-pork-bowl',
        name: 'BBQ Pulled Pork Bowl',
        description: 'Smoky pulled pork over fluffy rice with pickled slaw, corn and tangy BBQ drizzle.',
        imgUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A BBQ pulled pork bowl with rice, slaw and corn',
        isFavorite: true,
        category: 'Bowl',
        cuisine: 'American',
        tags: ['bowl', 'pork', 'bbq', 'comfort'],
        servings: 3,
        prepMinutes: 15,
        cookMinutes: 30,
        calories: 610,
        ingredients: [
            { id: 1201, name: 'Pork shoulder', quantity: 300, unit: 'g' },
            { id: 1202, name: 'BBQ sauce', quantity: 4, unit: 'tbsp' },
            { id: 1203, name: 'Rice', quantity: 200, unit: 'g' },
            { id: 1204, name: 'Coleslaw mix', quantity: 120, unit: 'g' },
            { id: 1205, name: 'Corn kernels', quantity: 100, unit: 'g' },
        ],
        durationMinutes: 45,
        difficulty: 'Medium',
        rating: 4.6,
        reviewCount: 1450,
        steps: [
            'Season pork and slow-cook or braise until fork-tender. Shred with two forks.',
            'Toss shredded pork with BBQ sauce. Char corn in a hot skillet until slightly blistered.',
            'Assemble bowls with rice, pulled pork, quick-pickled slaw and charred corn.',
        ],
        tips: 'Quick-pickle the slaw with rice vinegar and a pinch of sugar — the acidity cuts through the richness perfectly.',
        featured: false,
    },
    {
        id: 13,
        slug: 'mango-chicken-salad',
        name: 'Mango Chicken Salad',
        description: 'Crisp greens with grilled chicken, ripe mango, avocado and citrus-chili dressing.',
        imgUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A fresh mango chicken salad with avocado and mixed greens',
        isFavorite: false,
        category: 'Salad',
        cuisine: 'Fusion',
        tags: ['salad', 'chicken', 'mango', 'fresh'],
        servings: 2,
        prepMinutes: 15,
        cookMinutes: 10,
        calories: 380,
        ingredients: [
            { id: 1301, name: 'Chicken breast', quantity: 180, unit: 'g' },
            { id: 1302, name: 'Mango', quantity: 1, unit: 'each' },
            { id: 1303, name: 'Avocado', quantity: 1, unit: 'each' },
            { id: 1304, name: 'Mixed greens', quantity: 120, unit: 'g' },
            { id: 1305, name: 'Lime', quantity: 1, unit: 'each' },
        ],
        durationMinutes: 25,
        difficulty: 'Easy',
        rating: 4.3,
        reviewCount: 720,
        steps: [
            'Season chicken with salt, pepper and a pinch of chili. Grill until cooked through and slice.',
            'Dice mango and avocado. Whisk lime juice, olive oil and a touch of honey for the dressing.',
            'Arrange greens on plates, top with chicken, mango and avocado. Drizzle with citrus dressing.',
        ],
        tips: 'Use a just-ripe mango — too soft and it falls apart, too firm and you miss the sweetness.',
        featured: false,
    },
    {
        id: 14,
        slug: 'beef-teriyaki-stir-fry',
        name: 'Beef Teriyaki Stir-Fry',
        description: 'Tender beef strips glazed in homemade teriyaki with snap peas, peppers and steamed rice.',
        imgUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'Beef teriyaki stir-fry with vegetables and rice',
        isFavorite: false,
        category: 'Stir-Fry',
        cuisine: 'Asian',
        tags: ['stir-fry', 'beef', 'teriyaki', 'dinner'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 15,
        calories: 520,
        ingredients: [
            { id: 1401, name: 'Beef sirloin', quantity: 250, unit: 'g' },
            { id: 1402, name: 'Soy sauce', quantity: 3, unit: 'tbsp' },
            { id: 1403, name: 'Snap peas', quantity: 120, unit: 'g' },
            { id: 1404, name: 'Bell pepper', quantity: 1, unit: 'each' },
            { id: 1405, name: 'Rice', quantity: 180, unit: 'g' },
        ],
        durationMinutes: 25,
        difficulty: 'Medium',
        rating: 4.7,
        reviewCount: 1890,
        steps: [
            'Slice beef thin against the grain. Mix soy sauce, mirin, ginger and a teaspoon of brown sugar for the glaze.',
            'Sear beef in a screaming-hot pan for 1 minute per side. Remove and set aside.',
            'Stir-fry snap peas and peppers for 2 minutes. Return beef, pour in glaze and toss until sticky.',
        ],
        tips: 'Slice the beef against the grain and keep the pan screaming hot — this is how you get restaurant-quality sear at home.',
        featured: false,
    },
    {
        id: 15,
        slug: 'red-lentil-coconut-curry',
        name: 'Red Lentil Coconut Curry',
        description: 'Velvety lentils simmered in spiced coconut milk with tomatoes and fresh cilantro.',
        imgUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A warm bowl of red lentil curry with coconut cream swirl',
        isFavorite: true,
        category: 'Curry',
        cuisine: 'Fusion',
        tags: ['curry', 'vegan', 'lentils', 'comfort'],
        servings: 4,
        prepMinutes: 10,
        cookMinutes: 25,
        calories: 360,
        ingredients: [
            { id: 1501, name: 'Red lentils', quantity: 200, unit: 'g' },
            { id: 1502, name: 'Coconut milk', quantity: 400, unit: 'ml' },
            { id: 1503, name: 'Tomatoes', quantity: 200, unit: 'g' },
            { id: 1504, name: 'Cilantro', quantity: 1, unit: 'bunch' },
            { id: 1505, name: 'Curry powder', quantity: 2, unit: 'tbsp' },
        ],
        durationMinutes: 35,
        difficulty: 'Easy',
        rating: 4.4,
        reviewCount: 1320,
        steps: [
            'Sauté onion, garlic and ginger until fragrant. Add curry powder and toast for 30 seconds.',
            'Add lentils, diced tomatoes and coconut milk. Simmer for 20 minutes until lentils are soft.',
            'Season with salt and lime juice. Serve over rice topped with fresh cilantro.',
        ],
        tips: 'Red lentils break down naturally into a creamy texture — no blending needed. Stir occasionally to prevent sticking.',
        featured: false,
    },
    {
        id: 16,
        slug: 'ribeye-with-chimichurri',
        name: 'Ribeye with Chimichurri',
        description: 'Thick-cut ribeye with a bright herbaceous chimichurri and roasted fingerling potatoes.',
        imgUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A grilled ribeye steak topped with fresh chimichurri sauce',
        isFavorite: false,
        category: 'Steak',
        cuisine: 'American',
        tags: ['steak', 'grilled', 'herbs', 'dinner'],
        servings: 2,
        prepMinutes: 15,
        cookMinutes: 15,
        calories: 720,
        ingredients: [
            { id: 1601, name: 'Ribeye steak', quantity: 400, unit: 'g' },
            { id: 1602, name: 'Parsley', quantity: 1, unit: 'bunch' },
            { id: 1603, name: 'Red wine vinegar', quantity: 2, unit: 'tbsp' },
            { id: 1604, name: 'Fingerling potatoes', quantity: 300, unit: 'g' },
            { id: 1605, name: 'Garlic', quantity: 4, unit: 'cloves' },
        ],
        durationMinutes: 30,
        difficulty: 'Hard',
        rating: 4.9,
        reviewCount: 2780,
        steps: [
            'Make chimichurri: finely chop parsley, garlic, oregano. Mix with vinegar and olive oil. Rest 15 minutes.',
            'Bring ribeye to room temperature. Season heavily and sear over high heat, 4 minutes per side for medium-rare.',
            'Roast potatoes at 220°C until crisp. Rest steak 5 minutes, then slice and spoon chimichurri generously.',
        ],
        tips: 'Make chimichurri ahead — the flavors meld and intensify after 30 minutes. Never skip the resting step for steak.',
        featured: true,
    },
    {
        id: 17,
        slug: 'caprese-pasta-salad',
        name: 'Caprese Pasta Salad',
        description: 'Chilled fusilli with fresh mozzarella, ripe tomatoes, basil and balsamic glaze.',
        imgUrl: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A colorful caprese pasta salad with tomatoes, mozzarella and basil',
        isFavorite: false,
        category: 'Salad',
        cuisine: 'Italian',
        tags: ['salad', 'pasta', 'vegetarian', 'summer'],
        servings: 4,
        prepMinutes: 15,
        cookMinutes: 10,
        calories: 420,
        ingredients: [
            { id: 1701, name: 'Fusilli', quantity: 300, unit: 'g' },
            { id: 1702, name: 'Mozzarella', quantity: 200, unit: 'g' },
            { id: 1703, name: 'Tomatoes', quantity: 250, unit: 'g' },
            { id: 1704, name: 'Basil', quantity: 1, unit: 'bunch' },
            { id: 1705, name: 'Balsamic glaze', quantity: 2, unit: 'tbsp' },
        ],
        durationMinutes: 25,
        difficulty: 'Easy',
        rating: 4.2,
        reviewCount: 650,
        steps: [
            'Cook fusilli until al dente. Drain, rinse under cold water and toss with olive oil.',
            'Cube mozzarella and halve tomatoes. Tear basil leaves by hand.',
            'Combine everything in a large bowl. Drizzle with balsamic glaze, season with salt and pepper.',
        ],
        tips: 'Rinse pasta under cold water to stop cooking and keep it firm — this is the one time it is OK to do that.',
        featured: false,
    },
    {
        id: 18,
        slug: 'korean-bbq-beef-bowl',
        name: 'Korean BBQ Beef Bowl',
        description: 'Sweet-savory bulgogi beef over sticky rice with kimchi, pickled radish and a fried egg.',
        imgUrl: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A Korean BBQ beef bowl with kimchi, egg and pickled radish',
        isFavorite: true,
        category: 'Bowl',
        cuisine: 'Asian',
        tags: ['bowl', 'beef', 'korean', 'umami'],
        servings: 2,
        prepMinutes: 15,
        cookMinutes: 15,
        calories: 580,
        ingredients: [
            { id: 1801, name: 'Beef sirloin', quantity: 250, unit: 'g' },
            { id: 1802, name: 'Soy sauce', quantity: 3, unit: 'tbsp' },
            { id: 1803, name: 'Rice', quantity: 200, unit: 'g' },
            { id: 1804, name: 'Kimchi', quantity: 80, unit: 'g' },
            { id: 1805, name: 'Eggs', quantity: 2, unit: 'each' },
        ],
        durationMinutes: 30,
        difficulty: 'Medium',
        rating: 4.8,
        reviewCount: 2140,
        steps: [
            'Marinate thinly sliced beef in soy sauce, sesame oil, garlic, ginger and pear juice for 15 minutes.',
            'Cook rice. Sear marinated beef over high heat until caramelized. Fry eggs sunny-side up.',
            'Assemble bowls with rice, bulgogi beef, kimchi, pickled radish and fried egg on top.',
        ],
        tips: 'A little grated Asian pear in the marinade tenderizes the beef and adds natural sweetness.',
        featured: false,
    },
    {
        id: 19,
        slug: 'crispy-fish-tacos',
        name: 'Crispy Fish Tacos',
        description: 'Beer-battered fish in warm tortillas with crunchy cabbage, lime crema and pickled jalapeño.',
        imgUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'Crispy fish tacos with lime crema and purple cabbage slaw',
        isFavorite: false,
        category: 'Main Course',
        cuisine: 'Fusion',
        tags: ['tacos', 'seafood', 'crispy', 'street-food'],
        servings: 3,
        prepMinutes: 15,
        cookMinutes: 15,
        calories: 460,
        ingredients: [
            { id: 1901, name: 'White fish', quantity: 300, unit: 'g' },
            { id: 1902, name: 'Flour tortillas', quantity: 6, unit: 'each' },
            { id: 1903, name: 'Cabbage', quantity: 150, unit: 'g' },
            { id: 1904, name: 'Sour cream', quantity: 4, unit: 'tbsp' },
            { id: 1905, name: 'Lime', quantity: 2, unit: 'each' },
        ],
        durationMinutes: 30,
        difficulty: 'Medium',
        rating: 4.5,
        reviewCount: 1670,
        steps: [
            'Cut fish into strips. Dip in seasoned beer batter and fry until golden and crispy.',
            'Shred cabbage finely. Mix sour cream with lime juice and a pinch of cumin for the crema.',
            'Warm tortillas, fill with crispy fish, cabbage slaw and a generous drizzle of lime crema.',
        ],
        tips: 'Keep the oil at 180°C — too hot and the batter burns before the fish cooks through.',
        featured: false,
    },
    {
        id: 20,
        slug: 'wild-mushroom-risotto',
        name: 'Wild Mushroom Risotto',
        description: 'Creamy arborio rice with a medley of wild mushrooms, white wine and aged parmesan.',
        imgUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A plate of creamy wild mushroom risotto with shaved parmesan',
        isFavorite: false,
        category: 'Pasta',
        cuisine: 'Italian',
        tags: ['risotto', 'mushroom', 'comfort', 'vegetarian'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 35,
        calories: 480,
        ingredients: [
            { id: 2001, name: 'Arborio rice', quantity: 200, unit: 'g' },
            { id: 2002, name: 'Mixed mushrooms', quantity: 250, unit: 'g' },
            { id: 2003, name: 'White wine', quantity: 100, unit: 'ml' },
            { id: 2004, name: 'Parmesan', quantity: 60, unit: 'g' },
            { id: 2005, name: 'Vegetable broth', quantity: 750, unit: 'ml' },
        ],
        durationMinutes: 45,
        difficulty: 'Hard',
        rating: 4.6,
        reviewCount: 1560,
        steps: [
            'Sauté mushrooms in butter until golden and deeply fragrant. Season and set aside.',
            'Toast rice in olive oil. Deglaze with white wine. Add warm broth one ladle at a time, stirring continuously.',
            'When rice is creamy and al dente, fold in mushrooms, parmesan and a knob of butter.',
        ],
        tips: 'Never add cold broth — keep it warm beside the stove. Patience with stirring is what makes risotto silky.',
        featured: false,
    },
    {
        id: 21,
        slug: 'spicy-tuna-poke-bowl',
        name: 'Spicy Tuna Poke Bowl',
        description: 'Sushi-grade tuna over seasoned rice with cucumber, edamame, avocado and sriracha mayo.',
        imgUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A vibrant spicy tuna poke bowl with avocado and edamame',
        isFavorite: true,
        category: 'Bowl',
        cuisine: 'Asian',
        tags: ['bowl', 'tuna', 'raw', 'healthy'],
        servings: 2,
        prepMinutes: 15,
        cookMinutes: 15,
        calories: 440,
        ingredients: [
            { id: 2101, name: 'Sushi-grade tuna', quantity: 200, unit: 'g' },
            { id: 2102, name: 'Sushi rice', quantity: 200, unit: 'g' },
            { id: 2103, name: 'Avocado', quantity: 1, unit: 'each' },
            { id: 2104, name: 'Cucumber', quantity: 1, unit: 'each' },
            { id: 2105, name: 'Edamame', quantity: 80, unit: 'g' },
        ],
        durationMinutes: 30,
        difficulty: 'Easy',
        rating: 4.4,
        reviewCount: 930,
        steps: [
            'Cook sushi rice and season with rice vinegar, sugar and salt. Let cool to room temperature.',
            'Dice tuna into 1cm cubes. Toss with soy sauce, sesame oil and a dash of sriracha.',
            'Build bowls with rice, spicy tuna, sliced avocado, cucumber and edamame. Top with sesame seeds.',
        ],
        tips: 'Keep tuna ice-cold until serving. Use the sharpest knife you have for clean, even cubes.',
        featured: false,
    },
    {
        id: 22,
        slug: 'lamb-kofta-platter',
        name: 'Lamb Kofta Platter',
        description: 'Spiced lamb skewers with warm flatbread, tzatziki, pickled onions and fresh herbs.',
        imgUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A platter of lamb kofta skewers with tzatziki and flatbread',
        isFavorite: false,
        category: 'Main Course',
        cuisine: 'Mediterranean',
        tags: ['lamb', 'grilled', 'mediterranean', 'dinner'],
        servings: 4,
        prepMinutes: 20,
        cookMinutes: 15,
        calories: 560,
        ingredients: [
            { id: 2201, name: 'Ground lamb', quantity: 400, unit: 'g' },
            { id: 2202, name: 'Flatbread', quantity: 4, unit: 'each' },
            { id: 2203, name: 'Greek yogurt', quantity: 150, unit: 'g' },
            { id: 2204, name: 'Cucumber', quantity: 1, unit: 'each' },
            { id: 2205, name: 'Red onion', quantity: 1, unit: 'each' },
        ],
        durationMinutes: 35,
        difficulty: 'Hard',
        rating: 4.7,
        reviewCount: 1890,
        steps: [
            'Mix lamb with cumin, coriander, garlic, salt and pepper. Shape into oval koftas around skewers.',
            'Grill koftas over high heat for 3–4 minutes per side until charred outside and juicy inside.',
            'Make tzatziki with yogurt, grated cucumber, garlic and dill. Serve with warm flatbread and pickled onions.',
        ],
        tips: 'Chill the kofta mixture for 30 minutes before shaping — cold fat holds its shape better on the grill.',
        featured: false,
    },
    {
        id: 23,
        slug: 'shrimp-pad-thai',
        name: 'Shrimp Pad Thai',
        description: 'Rice noodles with plump shrimp, tamarind sauce, crushed peanuts and a squeeze of lime.',
        imgUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A plate of shrimp pad thai with peanuts and lime',
        isFavorite: false,
        category: 'Stir-Fry',
        cuisine: 'Thai',
        tags: ['noodles', 'shrimp', 'thai', 'street-food'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 15,
        calories: 490,
        ingredients: [
            { id: 2301, name: 'Rice noodles', quantity: 200, unit: 'g' },
            { id: 2302, name: 'Shrimp', quantity: 200, unit: 'g' },
            { id: 2303, name: 'Tamarind paste', quantity: 2, unit: 'tbsp' },
            { id: 2304, name: 'Peanuts', quantity: 3, unit: 'tbsp' },
            { id: 2305, name: 'Bean sprouts', quantity: 100, unit: 'g' },
        ],
        durationMinutes: 25,
        difficulty: 'Medium',
        rating: 4.8,
        reviewCount: 2560,
        steps: [
            'Soak rice noodles in warm water for 20 minutes. Mix tamarind paste, fish sauce and palm sugar for the sauce.',
            'Sear shrimp in a hot wok until pink. Push aside, scramble an egg, then add drained noodles.',
            'Pour sauce over noodles and toss until coated and slightly charred. Top with crushed peanuts, bean sprouts and lime.',
        ],
        tips: 'Don\'t over-soak the noodles — they should be pliable but still firm. The wok finishes the cooking.',
        featured: false,
    },
    {
        id: 24,
        slug: 'grilled-chicken-caesar-salad',
        name: 'Grilled Chicken Caesar Salad',
        description: 'Charred chicken over crisp romaine with creamy caesar dressing, croutons and shaved parmesan.',
        imgUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A classic grilled chicken caesar salad with croutons and parmesan',
        isFavorite: false,
        category: 'Salad',
        cuisine: 'American',
        tags: ['salad', 'chicken', 'classic', 'lunch'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 12,
        calories: 410,
        ingredients: [
            { id: 2401, name: 'Chicken breast', quantity: 200, unit: 'g' },
            { id: 2402, name: 'Romaine lettuce', quantity: 1, unit: 'head' },
            { id: 2403, name: 'Parmesan', quantity: 40, unit: 'g' },
            { id: 2404, name: 'Croutons', quantity: 60, unit: 'g' },
            { id: 2405, name: 'Anchovy paste', quantity: 1, unit: 'tsp' },
        ],
        durationMinutes: 22,
        difficulty: 'Easy',
        rating: 4.3,
        reviewCount: 1150,
        steps: [
            'Season chicken and grill over medium-high heat for 5–6 minutes per side. Let rest, then slice.',
            'Whisk anchovy paste, garlic, lemon juice, egg yolk and olive oil into a creamy dressing.',
            'Tear romaine, toss with dressing and croutons. Top with sliced chicken and shaved parmesan.',
        ],
        tips: 'Grill the romaine for 30 seconds per side — the slight char adds smoky complexity to a classic salad.',
        featured: false,
    },
    {
        id: 25,
        slug: 'butter-chicken-masala',
        name: 'Butter Chicken Masala',
        description: 'Tender chicken in a silky tomato-butter sauce with warm spices and a touch of cream.',
        imgUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A rich bowl of butter chicken masala with naan bread',
        isFavorite: true,
        category: 'Curry',
        cuisine: 'Fusion',
        tags: ['curry', 'chicken', 'creamy', 'spiced'],
        servings: 4,
        prepMinutes: 15,
        cookMinutes: 30,
        calories: 540,
        ingredients: [
            { id: 2501, name: 'Chicken thighs', quantity: 400, unit: 'g' },
            { id: 2502, name: 'Tomato passata', quantity: 300, unit: 'ml' },
            { id: 2503, name: 'Butter', quantity: 50, unit: 'g' },
            { id: 2504, name: 'Cream', quantity: 100, unit: 'ml' },
            { id: 2505, name: 'Garam masala', quantity: 2, unit: 'tbsp' },
        ],
        durationMinutes: 45,
        difficulty: 'Medium',
        rating: 4.9,
        reviewCount: 3420,
        steps: [
            'Marinate chicken in yogurt, garam masala, turmeric and chili. Sear until charred on all sides.',
            'In the same pan, cook onion, garlic and ginger. Add tomato passata and simmer for 15 minutes.',
            'Stir in butter and cream. Return chicken and simmer until sauce is velvety. Serve with rice or naan.',
        ],
        tips: 'The yogurt marinade is non-negotiable — it tenderizes the chicken and creates those charred edges.',
        featured: true,
    },
    {
        id: 26,
        slug: 'pan-seared-salmon-fillet',
        name: 'Pan-Seared Salmon Fillet',
        description: 'Crispy-skinned salmon with lemon-dill sauce, roasted asparagus and herbed couscous.',
        imgUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A pan-seared salmon fillet with asparagus and lemon sauce',
        isFavorite: false,
        category: 'Main Course',
        cuisine: 'Mediterranean',
        tags: ['salmon', 'seafood', 'healthy', 'elegant'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 15,
        calories: 490,
        ingredients: [
            { id: 2601, name: 'Salmon fillet', quantity: 300, unit: 'g' },
            { id: 2602, name: 'Asparagus', quantity: 200, unit: 'g' },
            { id: 2603, name: 'Couscous', quantity: 150, unit: 'g' },
            { id: 2604, name: 'Lemon', quantity: 1, unit: 'each' },
            { id: 2605, name: 'Dill', quantity: 2, unit: 'tbsp' },
        ],
        durationMinutes: 25,
        difficulty: 'Medium',
        rating: 4.6,
        reviewCount: 1740,
        steps: [
            'Pat salmon dry. Sear skin-side down in a hot pan for 4 minutes without moving. Flip and cook 2 more minutes.',
            'Roast asparagus with olive oil and salt at 200°C for 10 minutes until tender-crisp.',
            'Prepare couscous with lemon zest and dill. Plate with salmon and asparagus, finish with lemon-dill drizzle.',
        ],
        tips: 'Start skin-side down in a cold pan with oil — this renders the fat slowly and gives you glass-like crispy skin.',
        featured: false,
    },
    {
        id: 27,
        slug: 'chicken-tikka-skewers',
        name: 'Chicken Tikka Skewers',
        description: 'Yogurt-marinated chicken charred on skewers with mint chutney and warm naan.',
        imgUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'Charred chicken tikka skewers with mint chutney',
        isFavorite: false,
        category: 'Main Course',
        cuisine: 'Mediterranean',
        tags: ['chicken', 'grilled', 'spiced', 'skewers'],
        servings: 3,
        prepMinutes: 20,
        cookMinutes: 15,
        calories: 390,
        ingredients: [
            { id: 2701, name: 'Chicken thighs', quantity: 350, unit: 'g' },
            { id: 2702, name: 'Greek yogurt', quantity: 100, unit: 'g' },
            { id: 2703, name: 'Tikka spice mix', quantity: 2, unit: 'tbsp' },
            { id: 2704, name: 'Mint', quantity: 1, unit: 'bunch' },
            { id: 2705, name: 'Naan bread', quantity: 3, unit: 'each' },
        ],
        durationMinutes: 35,
        difficulty: 'Medium',
        rating: 4.5,
        reviewCount: 1080,
        steps: [
            'Cut chicken into chunks. Marinate in yogurt, tikka spice, lemon juice and garlic for at least 30 minutes.',
            'Thread onto skewers and grill or broil on high heat, turning every 3 minutes until charred.',
            'Blend mint with yogurt, lime juice and a pinch of salt for chutney. Serve with warm naan.',
        ],
        tips: 'Soak wooden skewers in water for 30 minutes before grilling to prevent them from burning.',
        featured: false,
    },
    {
        id: 28,
        slug: 'tofu-veggie-stir-fry',
        name: 'Tofu Veggie Stir-Fry',
        description: 'Crispy pressed tofu with seasonal vegetables in a ginger-garlic sauce over jasmine rice.',
        imgUrl: 'https://images.unsplash.com/photo-1607532941433-304659e8198a?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A colorful tofu and vegetable stir-fry over rice',
        isFavorite: false,
        category: 'Stir-Fry',
        cuisine: 'Asian',
        tags: ['tofu', 'vegan', 'stir-fry', 'healthy'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 12,
        calories: 340,
        ingredients: [
            { id: 2801, name: 'Firm tofu', quantity: 300, unit: 'g' },
            { id: 2802, name: 'Broccoli', quantity: 150, unit: 'g' },
            { id: 2803, name: 'Bell pepper', quantity: 1, unit: 'each' },
            { id: 2804, name: 'Ginger', quantity: 1, unit: 'thumb' },
            { id: 2805, name: 'Jasmine rice', quantity: 180, unit: 'g' },
        ],
        durationMinutes: 22,
        difficulty: 'Easy',
        rating: 4.1,
        reviewCount: 480,
        steps: [
            'Press tofu for 15 minutes, then cube. Pan-fry in oil until golden and crispy on all sides.',
            'Stir-fry broccoli and bell pepper in a hot wok with minced ginger and garlic for 3 minutes.',
            'Return tofu to the wok. Add soy sauce, sesame oil and a splash of rice vinegar. Toss and serve over rice.',
        ],
        tips: 'Press the tofu well — removing excess water is the single most important step for crispy tofu.',
        featured: false,
    },
    {
        id: 29,
        slug: 'filet-mignon-red-wine-sauce',
        name: 'Filet Mignon with Red Wine Sauce',
        description: 'Butter-basted filet mignon with a rich red wine reduction and creamy mashed potatoes.',
        imgUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A filet mignon steak with red wine sauce and mashed potatoes',
        isFavorite: false,
        category: 'Steak',
        cuisine: 'American',
        tags: ['steak', 'fine-dining', 'wine', 'special-occasion'],
        servings: 2,
        prepMinutes: 10,
        cookMinutes: 25,
        calories: 680,
        ingredients: [
            { id: 2901, name: 'Filet mignon', quantity: 350, unit: 'g' },
            { id: 2902, name: 'Red wine', quantity: 200, unit: 'ml' },
            { id: 2903, name: 'Butter', quantity: 3, unit: 'tbsp' },
            { id: 2904, name: 'Potatoes', quantity: 400, unit: 'g' },
            { id: 2905, name: 'Thyme', quantity: 3, unit: 'sprigs' },
        ],
        durationMinutes: 35,
        difficulty: 'Hard',
        rating: 4.8,
        reviewCount: 2890,
        steps: [
            'Sear filet mignon in a ripping-hot cast-iron pan for 3 minutes per side. Baste with butter and thyme.',
            'Deglaze pan with red wine, scraping up all fond. Reduce by half, then whisk in cold butter for a glossy sauce.',
            'Boil and mash potatoes with butter and cream until silky. Plate with filet and spoon sauce generously.',
        ],
        tips: 'Use a good drinking wine for the sauce — if you wouldn\'t drink it, don\'t cook with it.',
        featured: false,
    },
    {
        id: 30,
        slug: 'coconut-chickpea-curry-bowl',
        name: 'Coconut Chickpea Curry Bowl',
        description: 'Spiced chickpeas in creamy coconut broth with spinach, sweet potato and toasted naan crumbles.',
        imgUrl: 'https://images.unsplash.com/photo-1540914124281-342587941389?auto=format&fit=crop&w=1200&q=80',
        imageAlt: 'A warm coconut chickpea curry bowl with spinach and sweet potato',
        isFavorite: true,
        category: 'Bowl',
        cuisine: 'Thai',
        tags: ['bowl', 'curry', 'vegan', 'chickpea'],
        servings: 3,
        prepMinutes: 10,
        cookMinutes: 25,
        calories: 420,
        ingredients: [
            { id: 3001, name: 'Chickpeas', quantity: 400, unit: 'g' },
            { id: 3002, name: 'Coconut milk', quantity: 400, unit: 'ml' },
            { id: 3003, name: 'Sweet potato', quantity: 200, unit: 'g' },
            { id: 3004, name: 'Spinach', quantity: 100, unit: 'g' },
            { id: 3005, name: 'Naan bread', quantity: 2, unit: 'each' },
        ],
        durationMinutes: 35,
        difficulty: 'Medium',
        rating: 4.4,
        reviewCount: 870,
        steps: [
            'Sauté onion, garlic and ginger. Add cubed sweet potato and cook for 5 minutes.',
            'Add chickpeas, coconut milk and curry paste. Simmer for 20 minutes until sweet potato is tender.',
            'Stir in spinach until wilted. Serve in bowls with toasted naan crumbles and a squeeze of lime.',
        ],
        tips: 'Smash a few chickpeas against the side of the pot — it thickens the broth naturally without any flour.',
        featured: false,
    },
];